### ISSUE TITLE
First draft up.  Please review

### ISSUE THREAD

**Issue by roualdes** [roualdes/MATH131#1]
Hey @norcalbiostat and @njlytal, would you mind looking this over and making issues where you see fit?

**Comment by norcalbiostat** [comment]
General notes:

`week 00.ipynb`
    - after they copy the assignment, do you want them working in their own notebook? 
    - when they copy the assignment, how do they intentionally put it into their math 131 google drive folder? 
    - lot of exposition about markdown and latex. the density function chosen as an example could be intimidating. i'd advise not including this section since they won't actually be writing math (afaik)

from a 'pass this onto another instructor' POV... where are the ipynb's stored? (not that this matters right now)

**Comment by norcalbiostat** [comment]
Week 01: python basics

- love the easy to find links at the top
    - might want to put a note that says they should open in a new tab? 
- is a dictionary also like a hash table/lookup table? Is that *necessary* for this class? (note - i may ask lots of these types of questions. I'm not being critical - just trying to help keep it as simple as possible to start)
    -  looking at week 02 where you recode things, yup. makes sense to introduce now!
- also love the 'See also" callout boxes

`week-01-notes-ipynb`

Just found this nice shortcut
![image](https://github.com/roualdes/MATH131/assets/10426521/c7de8cd6-6b10-4fc5-897f-ca0bc4b6dc82)


`week-01-assignment.ipynb`

- when i click the assignment link, do I go to a common notebook? before i make a copy for myself? 
    -  this has the feel of a google document, where anyone can type and screw stuff up for others
    - I guarantee that people won't make copies of their own in this main document!!! 
        - Limitation we have to train out of them? 
        - Lock the main files to editing only by instructor and so they have to work in their own assignment? 
    - SCARY WARNING (shows up for each file it seems)
![image](https://github.com/roualdes/MATH131/assets/10426521/f1809b00-9e72-4d31-8b44-66709a9feb28)

- add code chunk place holders for all questions in week 1 assignment.

**Comment by norcalbiostat** [comment]
Week03 notes

Under aggregating - warning code showing up
![image](https://github.com/roualdes/MATH131/assets/10426521/2ccda93c-f732-46e9-86ac-2fbf87eb54f9)

seeing this in week 04 also

**Comment by norcalbiostat** [comment]
week 04 - reading in own data. 

- You show the function `pd.read_csv` for a csv file, and talk a little about file types, but don't cover tab delimited text or excel files
- I would argue against advocating that typing their own data into a spreadsheet is the easiest. i worry that students will download a data file for the project and then think they have to re-type it in to a spreadsheet. 

`week-04-assignment.ipynb`

- i wouldn't expect students to know how to convert the crime data to a csv file
- no explanation that i could see on why HSB has a different read function.

**Comment by norcalbiostat** [comment]
Week 5 / EDA

You have the written caveat that not all data on my data page is suitable for analysis on the `week-05.html`, but not on the `data.html` page.  
Is this last data page needed?

**Comment by roualdes** [comment]
This is great.  Thank you!

Let's do this one by one.  First up.

> after they copy the assignment, do you want them working in their own notebook?

Yes.  I added some words to make this more clear.

**Comment by roualdes** [comment]
> when they copy the assignment, how do they intentionally put it into their math 131 google drive folder?

I added some more words in the Week 00 Colab notebook Section Organizing files for MATH 131 to make this more clear.

**Comment by roualdes** [comment]
> lot of exposition about markdown and latex. the density function chosen as an example could be intimidating. i'd advise not including this section since they won't actually be writing math (afaik)

Agreed, they will probably not be writing math.  But I hate to miss an opportunity to show off LaTeX.  Plus this sub-section is short and leads with "We won't type much, if any, math in this course"

**Comment by roualdes** [comment]
> from a 'pass this onto another instructor' POV... where are the ipynb's stored? (not that this matters right now)

There are no .ipynbs.  This is all done in a flavor of Markdown.  So the week's Notes are files name as week-0x.md in the main directory of this repository.

**Comment by roualdes** [comment]
> might want to put a note that says they should open in a new tab?

Where do you think this note should go?

I just found an open issue in Jupyter Book asking for the ability to dictate when links open into a new tab.

**Comment by roualdes** [comment]
> is a dictionary also like a hash table/lookup table? Is that necessary for this class? (note - i may ask lots of these types of questions. I'm not being critical - just trying to help keep it as simple as possible to start)

Yes, Python dictionaries are effectively just hash tables.  I thought about this and want to keep it for mainly, but not exclusively, the two following reasons.  

* This leads into indexing a data frame, same syntax
* dict is an important data structure in Python

**Comment by roualdes** [comment]
> when i click the assignment link, do I go to a common notebook? before i make a copy for myself?

> this has the feel of a google document, where anyone can type and screw stuff up for others

> I guarantee that people won't make copies of their own in this main document!!! Limitation we have to train out of them?

> Lock the main files to editing only by instructor and so they have to work in their own assignment?

> this has the feel of a google document, where anyone can type and screw stuff up for others

> SCARY WARNING (shows up for each file it seems)

We'll have to train them out of this last one.

**Comment by roualdes** [comment]
> add code chunk place holders for all questions in week 1 assignment.

Meh, they'll have to learn how to add code cells eventually anyway, ya?

**Comment by roualdes** [comment]
> Under aggregating - warning code showing up

Can't avoid this as far as I know.  This is Pandas messaging that automatically shows up.

**Comment by roualdes** [comment]
> You show the function pd.read_csv for a csv file, and talk a little about file types, but don't cover tab delimited text or excel files

Don't I mention tabs as an option for delimiting values and then again in another few paragraphs?

I don't mention excel files, because in my head this section is about how data are stored and who knows how excel stores data.

Follow up thoughts here?

**Comment by roualdes** [comment]
> I would argue against advocating that typing their own data into a spreadsheet is the easiest. 

How do you have Bio students get data into R?

> i worry that students will download a data file for the project and then think they have to re-type it in to a spreadsheet.

Fair point.  I should add some words about not doing this for this class.

**Comment by roualdes** [comment]
> i wouldn't expect students to know how to convert the crime data to a csv file

Good catch.  Where should such instruction go?  

In Week 04 Notes?  That's not a bad idea.  But how does one address this issue?  It's different in Excel, Google Spreadsheets, Libre Office, ...

> no explanation that i could see on why HSB has a different read function.

Good catch.  Made a note to fix that tomorrow.

**Comment by roualdes** [comment]
> You have the written caveat that not all data on my data page is suitable for analysis on the week-05.html, but not on the data.html page.
Is this last data page needed?

Will you help me see this?  Maybe a direct quote or something.

**Comment by norcalbiostat** [comment]
> > when they copy the assignment, how do they intentionally put it into their math 131 google drive folder?
> 
> I added some more words in the Week 00 Colab notebook Section Organizing files for MATH 131 to make this more clear.

So I just opened my google drive and found that it automatically  added a `Colab Notebooks` folder in my google drive and put week00.ipynb in it. When I went back this AM and copied week01 assignment, it put it in the same folder.  I'm sorry, i should have tested this out yesterday. 

UNFORTUNATELY if you rename this folder to Math 131, then try to copy a new notebook, it makes a new `Colab Notebooks` folder. 

So.. is this enough folder organization for them? Do we think it matters if it's not named MATH 131? It keeps the same file name as you have it, (just renames it to "copy of..."), so it should all sort appropriately.

**Comment by norcalbiostat** [comment]
> > from a 'pass this onto another instructor' POV... where are the ipynb's stored? (not that this matters right now)
> 
> There are no .ipynbs. This is all done in a flavor of Markdown. So the week's Notes are files name as week-0x.md in the main directory of this repository.

I meant the actual colab notebooks. 
So like you added text to `week-00.ipynb` about folder org, but i can't find that exact file in this repo to make comments on.

**Comment by norcalbiostat** [comment]
> > I would argue against advocating that typing their own data into a spreadsheet is the easiest.
> 
> How do you have Bio students get data into R?

In my head, that's beyond the scope of this class. We give them nearly ready to use data in a format (txt/csv/xlsx) they're like to encounter and teach them how to get it into R/Python. 

> 
> > i worry that students will download a data file for the project and then think they have to re-type it in to a spreadsheet.
> 
> Fair point. I should add some words about not doing this for this class.

**Comment by roualdes** [comment]
> UNFORTUNATELY if you rename this folder to Math 131, then try to copy a new notebook, it makes a new Colab Notebooks folder.

Right.  The automatically created folder Colab Notebooks, in my head, is for miscellaneous notebooks.  I updated language to instruct students to create their own MATH131 folder and then move and rename notebooks.

**Comment by roualdes** [comment]
> I meant the actual colab notebooks.

I see.  These are all stored in my Google Drive account.  I'll add you as an editor.  Here are the links.

* [Week 00 Notes ipynb](https://colab.research.google.com/drive/1weKuFgd98W76BloyuuB4d2HudB5KLYew?usp=sharing)
* [Week 01 Notes ipynb](https://colab.research.google.com/drive/1VQhUmSxM6WfSw1ZZeKfhkRhkfM9JPXQx?usp=sharing)
* [Week 02 Notes ipynb](https://colab.research.google.com/drive/1qHzeZ_1RdfNe1l3KQsZi7xsSjLMVHbel?usp=sharing)
* [Week 03 Notes ipynb](https://colab.research.google.com/drive/1HqqhJvfHsWJAj_3dgBt0SOV5E90Sq1pG?usp=sharing)
* [Week 04 Notes ipynb](https://colab.research.google.com/drive/1FvGDi4MQxNzVOJRk6w07RWy3nnGNNF2K?usp=sharing)

* [Week 01 Assignment ipynb](https://colab.research.google.com/drive/1h9Ck7kWNN9_I2Yun9Yc4uBoI2lgv6chi?usp=sharing)
* [Week 02 Assignment ipynb](https://colab.research.google.com/drive/1os3hSTKNFblsA1MUTe25pvCjtaKfId30?usp=sharing)
* [Week 03 Assignment ipynb](https://colab.research.google.com/drive/1_ZTWGesIh5DUB_l3UdTmR5KK9AFPEy_9?usp=sharing)
* [Week 04 Assignment ipynb](https://colab.research.google.com/drive/1pn-YYBwmYQbjf8gmVyhv2zqPrmvQ4Bxm?usp=sharing)

**Comment by roualdes** [comment]
> In my head, that's beyond the scope of this class. We give them nearly ready to use data in a format (txt/csv/xlsx) they're like to encounter and teach them how to get it into R/Python.

I see your point.  I moved the section about entering data to Week 06: and beyond.  You're right this is better in multiple ways.

**Comment by norcalbiostat** [comment]
> > You have the written caveat that not all data on my data page is suitable for analysis on the week-05.html, but not on the data.html page.
> > Is this last data page needed?
> 
> Will you help me see this? Maybe a direct quote or something.

[line 76-102 on `week-05.md` ](https://github.com/roualdes/MATH131/blob/c4cdd0bedcb832b218ada1b9be725ed2da41a4fc/week-05.md?plain=1#L76)

i think my bigger question is  -- is the [data](https://roualdes.github.io/MATH131/data.html) page needed. Seems like duplicate info.

**Comment by roualdes** [comment]
I think I've addressed all your points thus far.  I'll push my updates now.  Let me know if you have any other comments for this issue. If not, I'll close this issue and ask that you open new issues for other/follow up comments/feedback.  

Thanks for helping :)
