### ISSUE TITLE
recommend removing `lst[::-1]`

### ISSUE THREAD

**Issue by norcalbiostat** [roualdes/MATH131#5]
https://github.com/roualdes/MATH131/blob/7ab23cb9fadb7575ff9f9e5d934fb9710cff55ad/week-01.md?plain=1#L289-L297

**Comment by roualdes** [comment]
Did you see that I put it in a sub-section "#### Advanced and optional (not required)"?  Is that good enough?

**Comment by norcalbiostat** [comment]
No i did not! Ty. that's fine. i had just gone in to write another note about the data frame section and thought to add that while i was there. apologies for not checking first.
