### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by norcalbiostat** [roualdes/MATH131#6]
https://github.com/roualdes/MATH131/blob/7ab23cb9fadb7575ff9f9e5d934fb9710cff55ad/week-01.md?plain=1#L468-L476

Is this supposed to be like how data frames are columns of vectors? I feel this has too much jargon/technical terminology. it took me two reads to figure out what you were saying. I think.

**Comment by roualdes** [comment]
Technically, R data frames are `list`s of `vector`s which print like columns, but yes.  That's exactly it.  And you got that after two reads?  That seems pretty good.  Maybe multiple paragraphs is a good compromise?

**Comment by norcalbiostat** [comment]
yes exactly, lists of vectors. which is why you can access them both using `$`. but i only understood the situation because i had a strong reference point? I will inherently learn python by connecting it to something similar in R etc.. 

i'm not trying to suggest paragraph structure. Just thinking out loud whether or not that depth/detail is needed. 
I have more thoughts.. but will put it in the hw01 where it connects to an answer of a hw that i'm struggling with.
